<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WordSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $words = [
            ['pan', 'de', 'pan', 'تابه / ماهیتابه', 'pan'],
            ['brief', 'de', 'letter', 'نامه', 'brief'],
            ['huis', 'het', 'house', 'خانه', 'hœys'],
            ['neus', 'de', 'nose', 'بینی', 'neus'],
            ['kind', 'het', 'child', 'کودک', 'kint'],
            ['ei', 'het', 'egg', 'تخم‌مرغ', 'ay'],
            ['lied', 'het', 'song', 'آهنگ / ترانه', 'leed'],
            ['blad', 'het', 'leaf / sheet', 'برگ / ورق', 'blat'],
            ['stad', 'de', 'city', 'شهر', 'stat'],
            ['pen', 'de', 'pen', 'خودکار', 'pen'],
            ['nek', 'de', 'neck', 'گردن', 'nek'],
            ['nep', 'de', 'fake', 'جعلی / تقلبی', 'nep'],
            ['pel', 'de', 'peel / skin', 'پوست', 'pel'],
            ['lek', 'de', 'leak', 'نشتی', 'lek'],
            ['zak', 'de', 'bag', 'کیسه', 'zak'],
            ['lesson', 'de', 'lesson', 'درس', 'les-uhn'],
            ['pil', 'de', 'pill', 'قرص', 'pil'],
            ['kop', 'de', 'cup', 'فنجان', 'kop'],
            ['pop', 'de', 'doll', 'عروسک', 'pop'],
            ['sop', 'de', 'soup', 'سوپ', 'sop'],
            ['map', 'de', 'folder / map', 'پوشه / نقشه', 'map'],
            ['pap', 'de', 'porridge', 'حریره', 'pap'],
            ['sap', 'het', 'juice', 'آبمیوه / شیره', 'sap'],
            ['man', 'de', 'man', 'مرد', 'man'],
            ['kan', 'de', 'jug / can', 'پارچ', 'kan'],
            ['pak', 'het', 'suit / package', 'کت و شلوار / بسته', 'pak'],
            ['melk', 'de', 'milk', 'شیر', 'melk'],
            ['miss', 'de', 'miss / lady', 'خانم', 'mis'],
            ['vis', 'de', 'fish', 'ماهی', 'vis'],
            ['kot', 'het', 'shed / small room', 'کلبه / اتاق کوچک', 'kot'],
            ['mok', 'de', 'mug', 'لیوان بزرگ', 'mok'],
            ['mos', 'het', 'moss', 'خزه', 'mos'],
            ['vos', 'de', 'fox', 'روباه', 'vos'],
            ['sok', 'de', 'sock', 'جوراب', 'sok'],
            ['raam', 'het', 'window', 'پنجره', 'raːm'],
            ['op', '', 'on / upon', 'روی', 'op'],
            ['bus', 'de', 'bus / mailbox', 'اتوبوس / صندوق پستی', 'bus'],
            ['lus', 'de', 'loop / loop of rope', 'حلقه / بند', 'lus'],
            ['gul', 'de', 'gul (generous)', 'سخاوتمند', 'gul'],
            ['gal', 'de', 'gall / bile', 'صفرا', 'gal'],
            ['log', 'het', 'log / piece of wood', 'تکه چوب', 'log'],
            ['tol', 'de', 'toll / spinning top', 'عوارض / فرفره', 'tol'],
            ['til', 'de', 'hoist / lift', 'بلند کردن / جرثقیل', 'til'],
            ['tal', 'het', 'number / count', 'عدد / شمار', 'tal'],
            ['leg', '', 'lay / position', 'قرار دادن', 'leg'],
            ['tel', 'de', 'count / number', 'شمردن / عدد', 'tel'],
            ['lak', 'de', 'varnish / paint', 'لاک / رنگ', 'lak'],
            ['neer', '', 'down / towards', 'پایین / به سمت', 'neer'],
            ['tot', '', 'until / up to', 'تا / تا زمانی که', 'tot'],
            ['stap', 'de', 'step', 'گام', 'stap'],
            ['kist', 'de', 'chest / box', 'صندوق', 'kist'],
            ['best', 'het', 'best / the best', 'بهترین', 'best'],
            ['knap', '', 'handsome / clever', 'خوش‌تیپ / زرنگ', 'knap'],
            ['knop', 'de', 'button / knob', 'دکمه / دسته', 'knop'],
            ['hink', 'de', 'hop / skip', 'پریدن / جستن', 'hink'],
            ['denk', '', 'think', 'فکر کردن', 'denk'],
            ['glas', 'het', 'glass', 'لیوان / شیشه', 'glas'],
            ['glom', '', 'gloom / darkness', 'تاریکی', 'glom'],
            ['wilg', 'de', 'willow', 'درخت بید', 'wilg'],
            ['telg', 'de', 'offspring / descendant', 'فرزند / نسل', 'telg'],
            ['slof', 'de', 'slipper', 'کفش روفرشی', 'slof'],
            ['slap', '', 'weak / limp', 'ضعیف / شل', 'slap'],
            ['pils', 'het', 'pilsner / beer', 'آبجو', 'pils'],
            ['hels', '', 'hellish / fierce', 'جهنمی / خشن', 'hels'],
            ['hink', 'de', 'hop / skip', 'پریدن / جستن', 'hink'],
            ['blijf', '', 'stay', 'بمان / باقی بمان', 'blayf'],
            ['plein', 'het', 'square', 'میدان', 'playn'],
            ['trein', 'de', 'train', 'قطار', 'trayn'],
            ['kruipt', '', 'crawls', 'می‌خزد / چهار دست و پا می‌رود', 'kroyp-t'],
            ['grond', 'de', 'ground / soil', 'زمین / خاک', 'gront'],
            ['vraag', 'de', 'question', 'سؤال / پرسش', 'vraakh'],
            ['maar', '', 'but', 'اما / ولی', 'maar'],
            ['ook', '', 'also / too', 'هم / همچنین', 'ook'],
            ['broer', 'de', 'brother', 'برادر', 'broor'],
            ['vast', '', 'fixed / tight', 'محکم / ثابت', 'vast'],
            ['stuur', 'het', 'steering / handlebar', 'فرمان', 'stuur'],
            ['dicht', '', 'closed / shut', 'بسته', 'dikht'],
            ['ster', 'de', 'star', 'ستاره', 'ster'],
            ['bij', 'de', 'bee', 'زنبور', 'bay'],
            ['maan', 'de', 'moon', 'ماه', 'maan'],
            ['bang', '', 'afraid / scared', 'ترسیده / خائف', 'bang'],
            ['rits', 'de', 'zipper', 'زیپ', 'rits'],
            ['boterham', 'de', 'sandwich / slice of bread', 'ساندویچ / برش نان', 'boh-ter-ham'],
            ['rijst', 'de', 'rice', 'برنج', 'rayst'],
            ['krant', 'de', 'newspaper', 'روزنامه', 'krant'],
            ['brood', 'het', 'bread', 'نان', 'brohd'],
            ['langzaam', '', 'slowly', 'آهسته / آرام', 'lang-zaam'],
            ['zingen', '', 'sing', 'آواز خواندن', 'zing-uhn'],
            ['lezen', '', 'read', 'خواندن', 'lay-zuhn'],
            ['menu', 'het', 'menu', 'منو', 'muh-nü'],
            ['lees', '', 'read (I read / imperative)', 'بخوان', 'lays'],
            ['spreek', '', 'speak (I speak / imperative)', 'صحبت کن / حرف بزن', 'sprayk'],
            ['kantoor', 'het', 'office', 'اداره / دفتر کار', 'kan-toor'],
            ['moet', '', 'must / have to', 'باید', 'moot'],
            ['weg', 'de', 'road / away', 'جاده / دور', 'vehkh'],
            ['verjaardag', 'de', 'birthday', 'تولد', 'ver-yar-dakh'],
            ['gefeliciteerd', '', 'congratulations', 'تبریک می‌گویم', 'khe-feh-li-si-teert'],
            ['graag', '', 'gladly / with pleasure', 'با رغبت / با میل', 'khraakh'],
            ['hartelijk', '', 'cordial / heartfelt', 'صمیمانه / از صمیم قلب', 'har-te-luk'],
            ['uitstekend', '', 'excellent', 'عالی / بسیار خوب', 'oyt-stay-kund'],
            ['vakantie', 'de', 'vacation / holiday', 'تعطیلات', 'va-kan-tsi'],
            ['voel', '', 'feel (I feel)', 'احساس می‌کنم', 'fool'],
            ['lekker', '', 'tasty / nice / good', 'خوشمزه / خوب / عالی', 'lek-ker'],
            ['straks', '', 'later / soon', 'بعداً / به‌زودی', 'straks'],
            ['net', '', 'just / just now', 'همین الان / تازه', 'net'],
            ['nu', '', 'now', 'الان', 'nu'],
            ['nou', '', 'well / so (filler)', 'خب / پس', 'now'],
            ['leuk', '', 'nice / fun', 'جالب / بامزه / خوب', 'loyk'],
            ['centrum', 'het', 'center / downtown', 'مرکز شهر', 'sen-trum'],
            ['welterusten', '', 'good night', 'شب بخیر', 'wel-te-rus-tun'],
            ['vraagwoorden', 'de', 'question words', 'کلمات پرسشی', 'vraakh-voor-dun'],
            ['vandaag', '', 'today', 'امروز', 'va-n-dakh'],
            ['vandaan', '', 'from / away from', 'از / از سمت', 'van-daan'],
            ['kaas', 'de', 'cheese', 'پنیر', 'kaas'],
            ['tegenstellingen', 'de', 'opposites', 'متضادها', 'tay-ghun-stel-ling-un'],
            ['oefening', 'de', 'exercise / practice', 'تمرین', 'oo-fuh-ning'],
            ['deze', '', 'this (plural/common)', 'این', 'day-zuh'],
            ['luistert', '', 'listens', 'گوش می‌دهد', 'lœys-tert'],
            ['antwoord', 'het', 'answer', 'پاسخ', 'ant-voort'],
            ['goede', '', 'good', 'خوب', 'khoo-duh'],
            ['daarna', '', 'after that', 'بعد از آن', 'daar-na'],
            ['uw', '', 'your (formal)', 'مال شما (رسمی)', 'uu'],
            ['ijsje', 'het', 'ice cream', 'بستنی', 'ays-yuh'],
            ['kijker', 'de', 'viewer / spectator', 'بیننده', 'kay-ker'],
            ['nieuwe', '', 'new', 'جدید', 'nee-wuh'],
            ['aflevering', 'de', 'episode', 'قسمت', 'af-lay-ve-ring'],
            ['eigenlijk', '', 'actually', 'در واقع', 'ay-ghun-luk'],
            ['nagedacht', '', 'thought about', 'فکر کرده', 'naa-guh-dakht'],
            ['onderwerp', 'het', 'subject / topic', 'موضوع', 'on-der-werp'],
            ['zouden', '', 'would', 'می‌بودند / می‌شد', 'zow-dun'],
            ['kunnen', '', 'can / be able to', 'توانستن', 'kun-nun'],
            ['bedenken', '', 'think of / invent', 'فکر کردن / ابداع کردن', 'buh-den-ken'],
            ['niks', '', 'nothing', 'هیچ‌چیز', 'niks'],
            ['toch', '', 'still / anyway', 'با این حال', 'tokh'],
            ['werkwoord', 'het', 'verb', 'فعل', 'verk-voort'],
            ['vaak', '', 'often', 'اغلب', 'vaak'],
            ['gebruikt', '', 'used', 'استفاده‌شده', 'khuh-broykt'],
            ['wordt', '', 'becomes / is (passive)', 'می‌شود', 'vort'],
            ['lopen', '', 'walk / run', 'راه رفتن', 'loh-pun'],
            ['vaker', '', 'more often', 'بیشتر اوقات', 'vaa-ker'],
            ['kreeg', '', 'got / received', 'گرفت', 'kraykh'],
            ['dat kan', '', 'that is possible', 'می‌شود / امکان دارد', 'dat kan'],
            ['meer', '', 'more', 'بیشتر', 'meer'],
            ['heel veel', '', 'a lot / very many', 'خیلی زیاد', 'heel feel'],
            ['weinig', '', 'little / few', 'کم', 'way-nikh'],
            ['te', '', 'too', 'خیلی / بیش از حد', 'tuh'],
            ['tijd', 'de', 'time', 'زمان', 'tayt'],
            ['voor', '', 'for / before', 'برای / قبل از', 'voor'],
            ['enzovoort', '', 'etcetera', 'و غیره', 'en-zo-voort'],
            ['echt', '', 'really', 'واقعاً', 'ekht'],
            ['ooit', '', 'ever / once', 'تا به حال', 'oyt'],
            ['geprobeerd', '', 'tried', 'امتحان کرده', 'khuh-pro-beert'],
            ['waarschijnlijk', '', 'probably', 'احتمالاً', 'waar-skhyn-luk'],
            ['blijf', '', 'stay', 'بمان', 'blayf'],
            ['leven', 'het', 'life', 'زندگی', 'lay-vun'],
            ['de buurt', 'de', 'the neighborhood', 'محله', 'burt'],
            ['nodig', '', 'needed', 'لازم', 'no-dikh'],
            ['graag', '', 'gladly / gladly like to', 'با میل', 'khraakh'],
            ['beter', '', 'better', 'بهتر', 'bay-ter'],
            ['makkelijker', '', 'easier', 'آسان‌تر', 'maa-kel-luk-er'],
            ['veel', '', 'many / much', 'زیاد', 'feel'],
            ['dingen', 'de', 'things', 'چیزها', 'ding-un'],
            ['bijvoorbeeld', '', 'for example', 'مثلاً', 'bay-voor-baylt'],
            ['vroeger', '', 'earlier / in the past', 'قبلاً', 'vroo-kher'],
            ['willekeurigs', 'het', 'something random', 'چیز تصادفی', 'vil-luh-koo-rikhs'],
            ['nemen', '', 'take', 'گرفتن', 'nay-mun'],
            ['nog', '', 'still / yet', 'هنوز', 'nokh'],
            ['gaat', '', 'goes', 'می‌رود', 'khaat'],
            ['flinke', '', 'considerable', 'قابل توجه', 'flin-kuh'],
            ['afstand', 'de', 'distance', 'فاصله', 'af-stant'],
            ['hardlopen', '', 'running', 'دویدن', 'hart-loh-pun'],
            ['blessure', 'de', 'injury', 'آسیب‌دیدگی', 'bleh-syur'],
            ['vervelend', '', 'annoying', 'آزاردهنده', 'fer-veh-lent'],
            ['moeilijk', '', 'difficult', 'سخت', 'moo-ee-luk'],
            ['omdat', '', 'because', 'چون', 'om-dat'],
            ['klopt', '', 'is correct', 'درست است', 'klopt'],
            ['steeds', '', 'constantly', 'مدام', 'steets'],
            ['kwijt', '', 'lost', 'گم‌شده', 'kwayt'],
            ['jammer', '', 'a pity', 'حیف', 'yam-mer'],
            ['elkaar', '', 'each other', 'یکدیگر', 'el-kar'],
            ['achter', '', 'behind / after', 'پشت / بعد از', 'akh-ter'],
            ['al', '', 'already', 'قبلاً', 'al'],
            ['gevoel', 'het', 'feeling', 'احساس', 'khuh-voel'],
            ['gezegd', '', 'said', 'گفته', 'khuh-zekht'],
            ['toen', '', 'then', 'آن‌وقت', 'toon'],
            ['wandelen', '', 'walking', 'پیاده‌روی', 'van-duh-lun'],
            ['verwacht', '', 'expect', 'انتظار داشتن', 'fer-vakht'],
            ['van hen', '', 'from them', 'از آن‌ها', 'van hen'],
            ['weten', '', 'know', 'دانستن', 'way-tun'],
            ['vindt', '', 'finds / thinks', 'فکر می‌کند', 'vint'],
            ['dat iemand', '', 'that someone', 'این‌که کسی', 'dat ee-mant'],
            ['praat', '', 'talks', 'صحبت می‌کند', 'praat'],
            ['moet je', '', 'you must', 'باید', 'moot yuh'],
            ['zelf', '', 'self', 'خود', 'zelf'],
            ['houden', '', 'keep / hold', 'نگه داشتن', 'how-dun'],
            ['inclusief', '', 'including', 'شامل / به‌همراه', 'in-klyu-seef'],
            ['ondertiteling', 'de', 'subtitles', 'زیرنویس', 'on-der-tee-ling'],
            ['aantal', 'het', 'number / amount', 'تعداد', 'aan-tal'],
            ['nuttige', '', 'useful', 'مفید', 'nut-ti-guh'],
            ['functies', 'de', 'functions / features', 'قابلیت‌ها', 'funk-tsies'],
            ['snelheid', 'de', 'speed', 'سرعت', 'snel-hayt'],
            ['aanpassen', '', 'adjust / customize', 'تنظیم کردن / تطبیق دادن', 'aan-pas-sun'],
            ['dus juist', '', 'so exactly / precisely', 'پس دقیقاً', 'dus-yuyst'],
            ['enthousiast', '', 'enthusiastic', 'مشتاق / پرانرژی', 'en-toe-zee-ast'],
            ['proberen', '', 'to try', 'امتحان کردن', 'pro-bee-run'],
            ['jaarabonnement', 'het', 'annual subscription', 'اشتراک سالانه', 'yaar-a-bo-ne-ment'],
            ['afsluiten', '', 'to take out / conclude', 'بستن / ثبت کردن', 'af-sloy-ten'],
            ['korting', 'de', 'discount', 'تخفیف', 'kor-ting'],
            ['goochelaar', 'de', 'magician', 'شعبده‌باز', 'khoo-khe-laar'],
            ['valt', '', 'falls / turns out', 'می‌افتد / می‌شود', 'valt'],
            ['regenen', '', 'to rain', 'باریدن (باران)', 'ray-ghu-nun'],
            ['schijnt', '', 'shines / seems', 'می‌تابد / به‌نظر می‌رسد', 'skhaynt'],
            ['heen', '', 'there / away', 'به آن‌جا', 'hayn'],
            ['herfst', 'de', 'autumn', 'پاییز', 'herfst'],
            ['misschien', '', 'maybe', 'شاید', 'mis-skhien'],
            ['doorbrengen', '', 'to spend (time)', 'سپری کردن', 'door-breng-un'],
            ['keertje', 'het', 'a little time / once', 'یک‌بار / کمی', 'keer-chuh'],
            ['erg', '', 'very / bad', 'خیلی / بد', 'erg'],
            ['handig', '', 'handy / useful', 'کاربردی / راحت', 'han-dikh'],
            ['als', '', 'if / as', 'اگر / مثل', 'als'],
            ['ging', '', 'went', 'رفت', 'khing'],
            ['taartje', 'het', 'small cake', 'کیک کوچک', 'taart-yuh'],
            ['beterschap', '', 'get well soon', 'بهبودی', 'bay-ter-skhap'],
            ['baan', 'de', 'job', 'شغل', 'baan'],
            ['zoeken', '', 'to search / look for', 'جستجو کردن', 'zoo-kun'],
            ['terugwerkende kracht', 'de', 'retroactive effect', 'اثر بازگشتی', 'te-rukh-ver-ken-duh krakht'],
            ['liever', '', 'rather / prefer', 'ترجیحاً', 'lee-ver'],
            ['gekund', '', 'could have', 'می‌توانست', 'khuh-kunt'],
            ['gekozen', '', 'chosen', 'انتخاب کرده', 'khuh-koo-zun'],
            ['boodschappen', 'de', 'groceries', 'خرید (مواد غذایی)', 'boot-skhap-pen'],
            ['vertel', '', 'tell (imperative)', 'بگو', 'fer-tel'],
            ['verhaal', 'het', 'story', 'داستان', 'fer-haal'],
            ['paar', 'het', 'pair / few', 'چند / جفت', 'paar'],
            ['woorden', 'de', 'words', 'کلمات', 'voor-dun'],
            ['keer', 'de', 'time / occasion', 'بار', 'keer'],
            ['probeer', '', 'try (imperative)', 'امتحان کن', 'pro-beer'],
            ['begrijpen', '', 'understand', 'فهمیدن', 'beh-gray-pun'],
            ['eraan', '', 'to it', 'به آن', 'er-aan'],
            ['buurt', 'de', 'neighborhood', 'محله', 'burt'],
            ['druk', '', 'busy', 'شلوغ', 'druk'],
            ['verschillende', '', 'different / various', 'مختلف', 'fer-skhil-len-duh'],
            ['winkel', 'de', 'shop', 'فروشگاه', 'vin-kel'],
            ['klanten', 'de', 'customers', 'مشتریان', 'klaan-ten'],
            ['kool', 'de', 'cabbage', 'کلم', 'kool'],
            ['vult', '', 'fills', 'پر می‌کند', 'vult'],
            ['rekken', 'de', 'shelves', 'قفسه‌ها', 'rek-ken'],
            ['haalt', '', 'gets / takes', 'برمی‌دارد', 'haalt'],
            ['voorraad', 'de', 'stock / supply', 'موجودی', 'voor-raad'],
            ['netjes', '', 'neatly', 'مرتب', 'net-yus'],
            ['alles', '', 'everything', 'همه‌چیز', 'al-les'],
            ['verzorgd', '', 'well-kept', 'مرتب / رسیدگی‌شده', 'fer-zor-kht'],
            ['de kassa', 'de', 'the checkout', 'صندوق', 'kas-sa'],
            ['scant', '', 'scans', 'اسکن می‌کند', 'skant'],
            ['producten', 'de', 'products', 'محصولات', 'pro-duk-ten'],
            ['snel', '', 'fast', 'سریع', 'snel'],
            ['rekent', '', 'calculates / charges', 'حساب می‌کند', 'ray-kent'],
            ['af', '', 'off / finished', 'تمام / قطع', 'af'],
            ['sommige', '', 'some', 'برخی', 'som-mi-guh'],
            ['betalen', '', 'pay', 'پرداخت کردن', 'be-taa-len'],
            ['contant', '', 'cash', 'نقدی', 'kon-tant'],
            ['opletten', '', 'pay attention', 'دقت کردن', 'op-let-ten'],
            ['winkelmandje', 'het', 'shopping basket', 'سبد خرید', 'vin-kel-mand-yuh'],
            ['winkelkar', 'de', 'shopping cart', 'چرخ خرید', 'vin-kel-kar'],
            ['verzamelen', '', 'collect', 'جمع‌آوری کردن', 'fer-zaa-me-len'],
            ['rij', 'de', 'queue / row', 'صف', 'ray'],
            ['weer', '', 'again', 'دوباره', 'weer'],
            ['praten', '', 'talk', 'صحبت کردن', 'praa-ten'],
            ['ervoor', '', 'for it / beforehand', 'برای آن', 'er-voor'],
            ['zorgt', '', 'takes care', 'مراقبت می‌کند', 'zorkht'],
            ['eigen', '', 'own', 'خود', 'ay-khen'],
        ];

        foreach ($words as [$de, $article, $en, $fa, $pron]) {
            $exists = DB::table('lesson_words')->where('nl_word', $de)->exists();
            if (! $exists) {
                DB::table('lesson_words')->insert([
                    'word_lesson_id' => 1,
                    'nl_word' => $de,
                    'article' => $article,
                    'nl_synonym' => null,
                    'en_word' => $en,
                    'pronunciation' => $pron,
                    'fa_meaning' => $fa,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }
    }
}
